page_blocks: [] 
_array_structures:
  page_blocks:
    - label: Banner blocks 
      icon: 
      value: 
        _id: banner-blocks 
        title: Banner block
        heading: This is a heading
        subtitle: This is a subtitle 
    - label: Text content
      icon: 
      value:
        _id: text-content
        title: text content block
        description_html: 
    - label: Video
      icon: 
      value:
        _id: video
        title: video block
    - label: Gallery
       icon: 
       value:
          _id: gallery 
          title: gallery block
          video: 
          video-type:

        
